config/routes.rb
Rails.application.routes.draw do
  resources :places, except: [:update, :edit, :destroy]
  root 'places#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  attr_accessor :raw_address
  geocoded_by :raw_address
  after_validation -> {
    self.address = self.raw_address
    geocode
  }, if: ->(obj){ obj.raw_address.present? and obj.raw_address !=obj.address }
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode, unless: ->(obj) { obj.raw_address.present? },
                     if: ->(obj){ obj.latitude.present? and obj.latitude_changed? and obj.longitude.present? and obj.longitude_changed? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.order('created_at DESC')
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = "Place Added!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @place = Place.find(params[:id])
  end

private

  def place_params
    params.require(:place).permit(:title, :raw_address, :latitude, :longitude, :visited_by)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MapperApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="assets/map.js" charset="utf-8"></script>
    <%= javascript_include_tag src: "https://maps.googleapis.com/maps/api/js?key=#{ENV['GMAPS_API_KEY']}&callback=initMap" 'async defer'%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f|%>
  <fieldset class="form-group">
    <%= f.label :title%>
    <%= f.text_field :title, class: 'form-control'%>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :visited_by%>
    <%= f.text_field :visited_by, class: 'form-control'%>
  </fieldset>

  <h4>Enter either address or coordinates</h4>
  <fieldset class="form-group">
    <%= f.label :raw_address, 'Address'%>
    <%= f.text_field :raw_address, class: 'form-control'%>
    <small class="text-muted">You can also enter IP. Your IP is <%= request.ip%></small>
  </fieldset>

  <div class="form-group row">
    <div class="col-sm-1">
      <%= f.label :latitude %>
    </div>

    <div class="col-sm-3">
      <%= f.text_field :latitude, class: "form-control" %>
    </div>

    <div class="col-sm-1">
      <%= f.label :longitude %>
    </div>

    <div class="col-sm-3">
      <%= f.text_field :longitude, class: "form-control" %>
    </div>
  </div>
  <%= f.submit "Add!", class: 'btn btn-primary'%>
<% end %>

<div class="card">
  <div class="card-block">
    <%= javascript_include_tag "map" %>
    <div id="map"></div>
  </div>
</div>

app/views/places/_place.html.erb
<li>
  <%= link_to place.title, place_path(place)%>
  visited by <strong><%=place.visited_by %></strong>
</li>

app/views/places/index.html.erb
<header><h1 class="display-4">Places</h1></header>

<%=link_to "Add Place", new_place_path, class: 'btn btn-primary btn-lg'%>

<div class="card">
  <div class="card-block">
    <ul>
      <%= render @places %>
    </ul>
  </div>
</div>

app/views/places/new.html.erb
<header><h1 class="display-4">Add Place</h1></header>

<%= render 'form'%>

app/views/places/show.html.erb
<header><h1 class="display-4"><%=@place.title%></h1></header>

<p>Address: <%= @place.address%></p>
<p>Coordinates: <%= @place.latitude%>, <%= @place.longitude%></p>


<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@place.latitude},#{@place.longitude}&markers=#{@place.latitude},#{@place.longitude}&zoom=7&size=640x400&key=#{ENV['GMAPS_API_KEY']}",
              class: 'img-fluid img-rounded', alt: "#{@place.title} on the map"%>